# Streamlit Secrets Configuration
# This file should be configured in Streamlit Cloud's secrets management
# DO NOT commit actual secrets to version control

# JIRA Configuration
JIRA_BASE_URL = "https://one-employee.atlassian.net/rest/api/3/"
JIRA_AUTH_TOKEN = "your-jira-auth-token-here"

# Gemini AI Configuration
GEMINI_API_KEY = "your-gemini-api-key-here"

# Application Configuration
APP_VERSION = "1.0.1"
APP_NAME = "JIRA Data Analyzer"

# Feature Flags
ENABLE_DATE_RANGE_FILTERING = "true"
ENABLE_ADVANCED_ANALYTICS = "true"

# Application Defaults
DEFAULT_JQL_QUERY = "labels IN (July2025)"
MAX_RESULTS_DEFAULT = "10000"
DEFAULT_FROM_MONTH = "July2025"
DEFAULT_TO_MONTH = "July2025"