# Streamlit Secrets Configuration for Cloud Deployment
# Copy and paste these exact values into Streamlit Cloud's secrets management

# JIRA Configuration
JIRA_BASE_URL = "https://one-employee.atlassian.net/rest/api/3/"
JIRA_AUTH_TOKEN = "bWlzLnN0ZjE2QGxuay5jby5pZDpBVEFUVDN4RmZHRjBTbjJtYmJOanBJb1NIWmRRbVJrd0lybW1VUUdrTVJwV1dYdHhTajVTTnRpZ0lhYTBfM3Z3dTlia3Zfd3VBTzZtbjZoN1BBc0txMnZkcTBZenQ4NEdGQ3lqTHpxM2ZXZGdnM0J3cUlXSHE1OGRNOGJGaGlmOVdMY1JZNHVCVWxZM010cTBqZlVBQkpuZUN3b0p2bXE0N0QzcHp5endLVV90WnlET2JCWEUwZXM9MzBBQjUzREQ="

# Gemini AI Configuration
GEMINI_API_KEY = "AIzaSyAkETc5NO5jRpDcNBoXq2M1L1cWZcp4tp8"

# Application Configuration
APP_VERSION = "1.0.1"
APP_NAME = "JIRA Data Analyzer"

# Feature Flags
ENABLE_DATE_RANGE_FILTERING = "true"
ENABLE_ADVANCED_ANALYTICS = "true"

# Application Defaults
DEFAULT_JQL_QUERY = "labels IN (July2025)"
MAX_RESULTS_DEFAULT = "10000"
DEFAULT_FROM_MONTH = "July2025"
DEFAULT_TO_MONTH = "July2025"

# DEBUG SETTINGS - Use these exact values in Streamlit Cloud
# Make sure each secret name matches exactly (case-sensitive)
# No extra spaces or characters
# Copy each line as: SECRET_NAME = "value"

# COPY THESE INTO STREAMLIT CLOUD SECRETS:
# JIRA_BASE_URL = "https://one-employee.atlassian.net/rest/api/3/"
# JIRA_AUTH_TOKEN = "bWlzLnN0ZjE2QGxuay5jby5pZDpBVEFUVDN4RmZHRjBTbjJtYmJOanBJb1NIWmRRbVJrd0lybW1VUUdrTVJwV1dYdHhTajVTTnRpZ0lhYTBfM3Z3dTlia3Zfd3VBTzZtbjZoN1BBc0txMnZkcTBZenQ4NEdGQ3lqTHpxM2ZXZGdnM0J3cUlXSHE1OGRNOGJGaGlmOVdMY1JZNHVCVWxZM010cTBqZlVBQkpuZUN3b0p2bXE0N0QzcHp5endLVV90WnlET2JCWEUwZXM9MzBBQjUzREQ="
# GEMINI_API_KEY = "AIzaSyAkETc5NO5jRpDcNBoXq2M1L1cWZcp4tp8"
# APP_VERSION = "1.0.1"
# APP_NAME = "JIRA Data Analyzer"
# ENABLE_DATE_RANGE_FILTERING = "true"
# ENABLE_ADVANCED_ANALYTICS = "true"
# DEFAULT_JQL_QUERY = "labels IN (July2025)"
# MAX_RESULTS_DEFAULT = "10000"
# DEFAULT_FROM_MONTH = "July2025"
# DEFAULT_TO_MONTH = "July2025"